# Zuul filter order
order:
  AccessFilter: 0
foo: 1234

# eureka.instance.status-page-url
status-page-url:
  suffix: 8760/swagger-ui.html

# 服务端口
server:
  port: 8760

# 服务名
spring:
  application:
    name: zuul

# Eureka
eureka:
  client:
    # 刷新本地缓存时间，默认30s
    registry-fetch-interval-seconds: 1

# Ribbon
ribbon:
  # Ribbon缓存刷新时间，默认为30秒
  ServerListRefreshInterval: 1000
  # 需考虑降低Ribbon的读取与连接超时上限
#  read-timeout: 60000
#  connect-timeout: 60000

# Zuul
zuul:
  routes:
    test1:
      path: /test1/**
      serviceId: test1
  add-host-header: true
  sensitive-headers: 
  host:
    connect-timeout-millis: 10000
    socket-timeout-millis: 60000
